services:
  gradio-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - .:/workspace
    command: bash -c "
      sleep 5 &&
      python /workspace/run.py"      
    env_file:
      - .env